INSERT INTO category_product(id, name, category_mum_id) VALUES (1, 'poissonnier', null)
INSERT INTO category_product(id, name, category_mum_id) VALUES (2, 'poisson', 1)
INSERT INTO category_product(id, name, category_mum_id) VALUES (3, 'fruit de mer', 1)
INSERT INTO category_product(id, name, category_mum_id) VALUES (4, 'primeur', null)
INSERT INTO category_product(id, name, category_mum_id) VALUES (5, 'fruit', 4)
INSERT INTO category_product(id, name, category_mum_id) VALUES (6, 'légume', 4)
INSERT INTO category_product(id, name, category_mum_id) VALUES (7, 'boucher/charcutier', null)
INSERT INTO category_product(id, name, category_mum_id) VALUES (8, 'boucherie', 7)
INSERT INTO category_product(id, name, category_mum_id) VALUES (9, 'charcuterie', 7)
INSERT INTO category_product(id, name, category_mum_id) VALUES (10, 'boeuf/veau/cheval', 8)
INSERT INTO category_product(id, name, category_mum_id) VALUES (11, 'agneau/chèvre/mouton', 8)
INSERT INTO category_product(id, name, category_mum_id) VALUES (12, 'volaille', 8)
INSERT INTO category_product(id, name, category_mum_id) VALUES (13, 'jambon', 9)
INSERT INTO category_product(id, name, category_mum_id) VALUES (14, 'andouille/boudin', 9)
INSERT INTO category_product(id, name, category_mum_id) VALUES (15, 'rillette/pâté/terrine', 9)
INSERT INTO category_product(id, name, category_mum_id) VALUES (16, 'saucisson', 9)
INSERT INTO category_product(id, name, category_mum_id) VALUES (17, 'crémier/fromager', null)
INSERT INTO category_product(id, name, category_mum_id) VALUES (18, 'lait', 17)
INSERT INTO category_product(id, name, category_mum_id) VALUES (19, 'fromage', 17)
INSERT INTO category_product(id, name, category_mum_id) VALUES (20, 'crème/beurre', 17)
INSERT INTO category_product(id, name, category_mum_id) VALUES (21, 'crème glacée', 17)
INSERT INTO category_product(id, name, category_mum_id) VALUES (22, 'yaourt', 17)
INSERT INTO category_product(id, name, category_mum_id) VALUES (23, 'boulanger', null)
INSERT INTO category_product(id, name, category_mum_id) VALUES (24, 'pain', 23)
INSERT INTO category_product(id, name, category_mum_id) VALUES (25, 'viennoiserie', 23)
INSERT INTO category_product(id, name, category_mum_id) VALUES (26, 'pâtisserie', 23)

INSERT INTO reference_product(id, name, date_referencing, category_product_id, sell_unit_id) VALUES (1, 'saumon d''élevage de Norvège', null, 2, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (2, 'cabillaud', null, 2, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (3, 'merlan', null, 2, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (4, 'crevette rose', null, 3, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (5, 'huitre de charente calibre 2', null, 3, null)

INSERT INTO reference_product(id, name, date_referencing, category_product_id, sell_unit_id) VALUES (6, 'filet de poulet jaune', null, 12, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (7, 'araignée de boeuf', null, 10, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (8, 'boudin noir', null, 14, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (9, 'rilletes du mans', null, 15, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (10, 'rosette de Lyon', null, 16, null)

INSERT INTO reference_product(id, name, date_referencing, category_product_id, sell_unit_id) VALUES (11, 'bleu d''Auvergne', null, 19, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (12, 'tomme de montagne au lait cru', null, 19, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (13, 'brie 60% matière grasse', null, 19, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (14, 'crème fraîche, pot de 40cl', null, 20, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (15, 'crème fouettée, bombe 250gr', null, 20, null)

INSERT INTO reference_product(id, name, date_referencing, category_product_id, sell_unit_id) VALUES (16, 'raisin noir', null, 5, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (17, 'pomme granny', null, 5, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (18, 'courgette', null, 6, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (19, 'poivron vert', null, 6, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (20, 'aubergine', null, 6, null)

INSERT INTO reference_product(id, name, date_referencing, category_product_id, sell_unit_id) VALUES (21, 'baguette tradition', null, 24, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (22, 'pain de campagne', null, 24, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (23, 'pain au chocolat', null, 25, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (24, 'chausson au pomme', null, 25, null)
INSERT INTO reference_product(id, name, date_referencing, category_product_id) VALUES (25, 'éclair au chocolat', null, 26, null)