INSERT INTO category_product(id,name,category_mum_id)VALUES(1,'Ebénistes - Menuisiers',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(2,'Cigarettes électroniques',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(3,'Animalerie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(4,'Librairie, papeterie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(5,'Informatique',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(6,'Téléphonie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(7,'Téléphonie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(8,'Fleuriste',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(9,'Instruments de musique',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(10,'Jeux, Jouets, Modélisme',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(11,'Maroquinerie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(12,'Lingerie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(13,'Mercerie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(14,'Opticien',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(15,'Parfumerie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(16,'Bijoutiers - horlogers',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(17,'Antiquités, Brocantes',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(18,'Chaussures',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(19,'Auto, motocycles',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(20,'Cordonniers, clé minute',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(21,'Parapharmacie',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(22,'Décoration, arts de la table, cadeaux',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(23,'Electroménager, TV, Son',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(24,'Prête-à-porter',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(25,'Articles de sport',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(26,'Encadrement',null)
INSERT INTO category_product(id,name,category_mum_id)VALUES(27,'Fêtes et déguisements',1)
INSERT INTO category_product(id,name,category_mum_id)VALUES(28,'Charpentier',1)
INSERT INTO category_product(id,name,category_mum_id)VALUES(29,'Menuisier',1)
INSERT INTO category_product(id,name,category_mum_id)VALUES(30,'Cigarettes électroniques',2)
INSERT INTO category_product(id,name,category_mum_id)VALUES(31,'E-liquides',2)
INSERT INTO category_product(id,name,category_mum_id)VALUES(32,'Accessoires',2)
INSERT INTO category_product(id,name,category_mum_id)VALUES(33,'Animaux de la ferme',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(34,'Animaux sauvages',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(35,'Aquariophilie',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(36,'Chiens',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(37,'Chats',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(38,'Oiseaux',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(39,'Reptiles & Co',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(40,'Rongeurs & Co',3)
INSERT INTO category_product(id,name,category_mum_id)VALUES(41,'Accessoire',33)
INSERT INTO category_product(id,name,category_mum_id)VALUES(42,'Alimentation',33)
INSERT INTO category_product(id,name,category_mum_id)VALUES(43,'Hygiène & soins',33)
INSERT INTO category_product(id,name,category_mum_id)VALUES(44,'Accessoire',34)
INSERT INTO category_product(id,name,category_mum_id)VALUES(45,'Alimentation',34)
INSERT INTO category_product(id,name,category_mum_id)VALUES(46,'Hygiène & soins',34)
INSERT INTO category_product(id,name,category_mum_id)VALUES(47,'Accessoire',35)
INSERT INTO category_product(id,name,category_mum_id)VALUES(48,'Alimentation',35)
INSERT INTO category_product(id,name,category_mum_id)VALUES(49,'Hygiène & soins',35)
INSERT INTO category_product(id,name,category_mum_id)VALUES(50,'Accessoire',36)
INSERT INTO category_product(id,name,category_mum_id)VALUES(51,'Alimentation',36)
INSERT INTO category_product(id,name,category_mum_id)VALUES(52,'Hygiène & soins',36)
INSERT INTO category_product(id,name,category_mum_id)VALUES(53,'Accessoire',37)
INSERT INTO category_product(id,name,category_mum_id)VALUES(54,'Alimentation',37)
INSERT INTO category_product(id,name,category_mum_id)VALUES(55,'Hygiène & soins',37)
INSERT INTO category_product(id,name,category_mum_id)VALUES(56,'Accessoire',38)
INSERT INTO category_product(id,name,category_mum_id)VALUES(57,'Alimentation',38)
INSERT INTO category_product(id,name,category_mum_id)VALUES(58,'Hygiène & soins',38)
INSERT INTO category_product(id,name,category_mum_id)VALUES(59,'Accessoire',39)
INSERT INTO category_product(id,name,category_mum_id)VALUES(60,'Alimentation',39)
INSERT INTO category_product(id,name,category_mum_id)VALUES(61,'Hygiène & soins',39)
INSERT INTO category_product(id,name,category_mum_id)VALUES(62,'Accessoire',40)
INSERT INTO category_product(id,name,category_mum_id)VALUES(63,'Alimentation',40)
INSERT INTO category_product(id,name,category_mum_id)VALUES(64,'Hygiène & soins',40)
INSERT INTO category_product(id,name,category_mum_id)VALUES(65,'Librairie',4)
INSERT INTO category_product(id,name,category_mum_id)VALUES(66,'Papeterie',4)
INSERT INTO category_product(id,name,category_mum_id)VALUES(67,'Livres',65)
INSERT INTO category_product(id,name,category_mum_id)VALUES(68,'BD, Mangas',65)
INSERT INTO category_product(id,name,category_mum_id)VALUES(69,'Ecriture ',66)
INSERT INTO category_product(id,name,category_mum_id)VALUES(70,'Dessin/Peinture',66)
INSERT INTO category_product(id,name,category_mum_id)VALUES(71,'Cahier/Feuilles',66)
INSERT INTO category_product(id,name,category_mum_id)VALUES(72,'Petites fournitures',66)
INSERT INTO category_product(id,name,category_mum_id)VALUES(73,'Logiciels',5)
INSERT INTO category_product(id,name,category_mum_id)VALUES(74,'Ordinateurs',5)
INSERT INTO category_product(id,name,category_mum_id)VALUES(75,'Consoles de jeux',5)
INSERT INTO category_product(id,name,category_mum_id)VALUES(76,'Jeux vidéos',5)
INSERT INTO category_product(id,name,category_mum_id)VALUES(77,'Ordinateur de bureau',74)
INSERT INTO category_product(id,name,category_mum_id)VALUES(78,'Ordinateur portable',74)
INSERT INTO category_product(id,name,category_mum_id)VALUES(79,'Composants',74)
INSERT INTO category_product(id,name,category_mum_id)VALUES(80,'Accessoires',74)
INSERT INTO category_product(id,name,category_mum_id)VALUES(81,'Consoles de salon',75)
INSERT INTO category_product(id,name,category_mum_id)VALUES(82,'Consoles portables',75)
INSERT INTO category_product(id,name,category_mum_id)VALUES(83,'Accessoires',75)
INSERT INTO category_product(id,name,category_mum_id)VALUES(84,'Pour consoles de salon',76)
INSERT INTO category_product(id,name,category_mum_id)VALUES(85,'Pour consoles portables',76)
INSERT INTO category_product(id,name,category_mum_id)VALUES(86,'Pour ordinateur',76)
INSERT INTO category_product(id,name,category_mum_id)VALUES(87,'Jeux rétro',76)
INSERT INTO category_product(id,name,category_mum_id)VALUES(88,'Téléphones fixes',6)
INSERT INTO category_product(id,name,category_mum_id)VALUES(89,'Téléphones Mobiles',6)
INSERT INTO category_product(id,name,category_mum_id)VALUES(90,'Accessoires',6)
INSERT INTO category_product(id,name,category_mum_id)VALUES(91,'Bouquets de fleurs',7)
INSERT INTO category_product(id,name,category_mum_id)VALUES(92,'Plantes',7)
INSERT INTO category_product(id,name,category_mum_id)VALUES(93,'Instruments à corde',8)
INSERT INTO category_product(id,name,category_mum_id)VALUES(94,'Instruments à vent (cuivre)',8)
INSERT INTO category_product(id,name,category_mum_id)VALUES(95,'Instruments à vent (bois)',8)
INSERT INTO category_product(id,name,category_mum_id)VALUES(96,'Percussions',8)
INSERT INTO category_product(id,name,category_mum_id)VALUES(97,'Jeux de société',9)
INSERT INTO category_product(id,name,category_mum_id)VALUES(98,'Jouets',9)
INSERT INTO category_product(id,name,category_mum_id)VALUES(99,'Modélisme',9)
INSERT INTO category_product(id,name,category_mum_id)VALUES(100,'Sacs',10)
INSERT INTO category_product(id,name,category_mum_id)VALUES(101,'Porte-feuilles',10)
INSERT INTO category_product(id,name,category_mum_id)VALUES(102,'Divers',10)
INSERT INTO category_product(id,name,category_mum_id)VALUES(103,'Soutiens-gorges',11)
INSERT INTO category_product(id,name,category_mum_id)VALUES(104,'Culottes/strings',11)
INSERT INTO category_product(id,name,category_mum_id)VALUES(105,'Porte-jarretelles',11)
INSERT INTO category_product(id,name,category_mum_id)VALUES(106,'Lingerie sculptante',11)
INSERT INTO category_product(id,name,category_mum_id)VALUES(107,'Caracos/bodys/corsets',11)
INSERT INTO category_product(id,name,category_mum_id)VALUES(108,'Accessoires de mercerie',12)
INSERT INTO category_product(id,name,category_mum_id)VALUES(109,'Boutons',12)
INSERT INTO category_product(id,name,category_mum_id)VALUES(110,'Rubans',12)
INSERT INTO category_product(id,name,category_mum_id)VALUES(111,'Tissus et coupons',12)
INSERT INTO category_product(id,name,category_mum_id)VALUES(112,'Fils',12)
INSERT INTO category_product(id,name,category_mum_id)VALUES(113,'Tricots',12)
INSERT INTO category_product(id,name,category_mum_id)VALUES(114,'Lunettes de vue',13)
INSERT INTO category_product(id,name,category_mum_id)VALUES(115,'Lunettes de soleil',13)
INSERT INTO category_product(id,name,category_mum_id)VALUES(116,'Lentilles',13)
INSERT INTO category_product(id,name,category_mum_id)VALUES(117,'Parfum',14)
INSERT INTO category_product(id,name,category_mum_id)VALUES(118,'Maquillage',14)
INSERT INTO category_product(id,name,category_mum_id)VALUES(119,'Femme',117)
INSERT INTO category_product(id,name,category_mum_id)VALUES(120,'Homme',117)
INSERT INTO category_product(id,name,category_mum_id)VALUES(121,'Teint',118)
INSERT INTO category_product(id,name,category_mum_id)VALUES(122,'Yeux',118)
INSERT INTO category_product(id,name,category_mum_id)VALUES(123,'Lèvres',118)
INSERT INTO category_product(id,name,category_mum_id)VALUES(124,'Ongles',118)
INSERT INTO category_product(id,name,category_mum_id)VALUES(125,'Bijoutiers',15)
INSERT INTO category_product(id,name,category_mum_id)VALUES(126,'Horlogers',15)
INSERT INTO category_product(id,name,category_mum_id)VALUES(127,'Estimation & débarras',16)
INSERT INTO category_product(id,name,category_mum_id)VALUES(128,'Meubles & décoration',16)
INSERT INTO category_product(id,name,category_mum_id)VALUES(129,'Objet & bibelots',16)
INSERT INTO category_product(id,name,category_mum_id)VALUES(130,'Or, Argent, Fourrure',16)
INSERT INTO category_product(id,name,category_mum_id)VALUES(131,'Homme',17)
INSERT INTO category_product(id,name,category_mum_id)VALUES(132,'Femme',17)
INSERT INTO category_product(id,name,category_mum_id)VALUES(133,'Garçon',17)
INSERT INTO category_product(id,name,category_mum_id)VALUES(134,'Fille',17)
INSERT INTO category_product(id,name,category_mum_id)VALUES(135,'Bébé',17)
INSERT INTO category_product(id,name,category_mum_id)VALUES(136,'Automobiles',18)
INSERT INTO category_product(id,name,category_mum_id)VALUES(137,'Moto/Motocycles',18)
INSERT INTO category_product(id,name,category_mum_id)VALUES(138,'Cordonnerie',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(139,'Clés',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(140,'Gravure',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(141,'plaques d''immatriculation',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(142,'Tampons',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(143,'Porte-clés',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(144,'Chaussettes',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(145,'Télécommandes',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(146,'Cadenas',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(147,'Coques de clé',19)
INSERT INTO category_product(id,name,category_mum_id)VALUES(148,'Santé',20)
INSERT INTO category_product(id,name,category_mum_id)VALUES(149,'Beauté',20)
INSERT INTO category_product(id,name,category_mum_id)VALUES(150,'Grossesse/bébé',20)
INSERT INTO category_product(id,name,category_mum_id)VALUES(151,'Premier secours',148)
INSERT INTO category_product(id,name,category_mum_id)VALUES(152,'Douleur-maux',148)
INSERT INTO category_product(id,name,category_mum_id)VALUES(153,'Compléments santé',148)
INSERT INTO category_product(id,name,category_mum_id)VALUES(154,'Yeux/nez/oreilles',148)
INSERT INTO category_product(id,name,category_mum_id)VALUES(155,'Matériel médical',148)
INSERT INTO category_product(id,name,category_mum_id)VALUES(156,'Sexualité',148)
INSERT INTO category_product(id,name,category_mum_id)VALUES(157,'Vétérinaire',148)
INSERT INTO category_product(id,name,category_mum_id)VALUES(158,'Visage',149)
INSERT INTO category_product(id,name,category_mum_id)VALUES(159,'Corps',149)
INSERT INTO category_product(id,name,category_mum_id)VALUES(160,'Hygiène',149)
INSERT INTO category_product(id,name,category_mum_id)VALUES(161,'Minceur',149)
INSERT INTO category_product(id,name,category_mum_id)VALUES(162,'Hygiène bébé',150)
INSERT INTO category_product(id,name,category_mum_id)VALUES(163,'Couches - changes',150)
INSERT INTO category_product(id,name,category_mum_id)VALUES(164,'Biberons - Accessoires',150)
INSERT INTO category_product(id,name,category_mum_id)VALUES(165,'Alimentation bébé',150)
INSERT INTO category_product(id,name,category_mum_id)VALUES(166,'Futures maman',150)
INSERT INTO category_product(id,name,category_mum_id)VALUES(167,'Décorations vitrine',21)
INSERT INTO category_product(id,name,category_mum_id)VALUES(168,'Arts de la table',21)
INSERT INTO category_product(id,name,category_mum_id)VALUES(169,'Cadeaux',21)
INSERT INTO category_product(id,name,category_mum_id)VALUES(170,'Electroménager',22)
INSERT INTO category_product(id,name,category_mum_id)VALUES(171,'TV',22)
INSERT INTO category_product(id,name,category_mum_id)VALUES(172,'Son',22)
INSERT INTO category_product(id,name,category_mum_id)VALUES(173,'Photo',22)
INSERT INTO category_product(id,name,category_mum_id)VALUES(174,'Lavage - séchage',170)
INSERT INTO category_product(id,name,category_mum_id)VALUES(175,'Froid',170)
INSERT INTO category_product(id,name,category_mum_id)VALUES(176,'Cuisson',170)
INSERT INTO category_product(id,name,category_mum_id)VALUES(177,'Arts culinaires',170)
INSERT INTO category_product(id,name,category_mum_id)VALUES(178,'Entretien de la maison',170)
INSERT INTO category_product(id,name,category_mum_id)VALUES(179,'Beauté - Hygiène',170)
INSERT INTO category_product(id,name,category_mum_id)VALUES(180,'Téléviseur',171)
INSERT INTO category_product(id,name,category_mum_id)VALUES(181,'Home cinema',171)
INSERT INTO category_product(id,name,category_mum_id)VALUES(182,'Vidéoprojecteur',171)
INSERT INTO category_product(id,name,category_mum_id)VALUES(183,'Récepteur - Décodeur',171)
INSERT INTO category_product(id,name,category_mum_id)VALUES(184,'Lecteur - Enregistreur',171)
INSERT INTO category_product(id,name,category_mum_id)VALUES(185,'Meuble / Support TV',171)
INSERT INTO category_product(id,name,category_mum_id)VALUES(186,'Casque audio',172)
INSERT INTO category_product(id,name,category_mum_id)VALUES(187,'Enceinte bluetooth - MP3 - MP4',172)
INSERT INTO category_product(id,name,category_mum_id)VALUES(188,'Radio - Reveil - Dictaphone',172)
INSERT INTO category_product(id,name,category_mum_id)VALUES(189,'Hifi de salon',172)
INSERT INTO category_product(id,name,category_mum_id)VALUES(190,'Platine / Disques / Vinyles',172)
INSERT INTO category_product(id,name,category_mum_id)VALUES(191,'Appareil photo',173)
INSERT INTO category_product(id,name,category_mum_id)VALUES(192,'Objectif - Flash',173)
INSERT INTO category_product(id,name,category_mum_id)VALUES(193,'Studio photo',173)
INSERT INTO category_product(id,name,category_mum_id)VALUES(194,'Camera Sport',173)
INSERT INTO category_product(id,name,category_mum_id)VALUES(195,'Camescope',173)
INSERT INTO category_product(id,name,category_mum_id)VALUES(196,'Observation - Espionnage',173)
INSERT INTO category_product(id,name,category_mum_id)VALUES(197,'Cadre photo numérique',173)
INSERT INTO category_product(id,name,category_mum_id)VALUES(198,'Enfant',23)
INSERT INTO category_product(id,name,category_mum_id)VALUES(199,'Femme',23)
INSERT INTO category_product(id,name,category_mum_id)VALUES(200,'Homme',23)
INSERT INTO category_product(id,name,category_mum_id)VALUES(201,'Pulls / gilets',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(202,'Vestes / Manteaux',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(203,'T-shirts / débardeurs',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(204,'Robes',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(205,'Jupes',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(206,'Jeans / Pantalons / Shorts / Leggings',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(207,'Chaussettes/collants',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(208,'Sous-vêtements/pyjamas',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(209,'Sports',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(210,'Maillots de bain / Peignoirs',198)
INSERT INTO category_product(id,name,category_mum_id)VALUES(211,'T-shirts / Tops',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(212,'Chemisiers / Tuniques',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(213,'Pulls / gilets',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(214,'Vestes',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(215,'Manteaux',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(216,'Robes',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(217,'Jupes',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(218,'Jeans / Pantalons / Shorts / Leggings',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(219,'Chaussettes / collants',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(220,'Pyjamas /Nuisettes',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(221,'Sports',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(222,'Maillots de bain / Peignoirs',199)
INSERT INTO category_product(id,name,category_mum_id)VALUES(223,'T-shirts / Polos',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(224,'Chemises',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(225,'Pulls / gilets',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(226,'Vestes',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(227,'Manteaux',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(228,'Jeans / Pantalons / Shorts',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(229,'Costumes / Cravates',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(230,'Sous-vêtements/pyjamas',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(231,'Sports',200)
INSERT INTO category_product(id,name,category_mum_id)VALUES(232,'Maillots de bain / Peignoirs',200)
